name: CI
#run-name: 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
concurrency:
  # Cancel the previous builds in the same PR.
  # Allow running concurrently for all non-PR commits.
  group: ci-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
jobs:
  build-project:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Install Redis
      uses: supercharge/redis-github-action@1.5.0
      with:
        # TLS Support starts from v6.0.
        redis-port: 6379
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
